### ISSUE TITLE
[Request] Commandline Addition for Aligncamera set states

### ISSUE THREAD

**Issue by VeraNala** [awgil/ffxiv_navmesh#23]
Current implementation is a toggled state for "/vnav aligncamera"
I would like to request for the expansion of this to include "/vnav aligncamera on" and "/vnav aligncamera off" or something similar for macros and AD usage, as the preexisting state might not be known (in case of AD paths) or have changed from last use, causing inversions of expected and intended behaviour.

**Comment by awgil** [comment]
PR merged, will be available in next version.
